# =============================================================================
#  ThinkPad T480s — top-level NixOS configuration
#  Imports every system-level module under ./nixos/*.nix
# =============================================================================
{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by `nixos-generate-config`
    ./boot.nix
    ./networking.nix
    ./power.nix
    ./hyprland.nix
    ./greetd.nix
    ./users.nix
    ./nix-settings.nix
  ];

  # ── System identity ──────────────────────────────────────────────────────
  system.stateVersion = "24.11";
  system.autoUpgrade.enable = false;       # manage upgrades manually
  system.autoUpgrade.allowReboot = false;

  # ── Locale / console ─────────────────────────────────────────────────────
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.supportedLocales = [ "en_US.UTF-8" "de_DE.UTF-8" ];
  console.keyMap = "us";
  console.font = "Lat2-Terminus16";
  console.useXkbConfig = true;

  # ── Timezone ─────────────────────────────────────────────────────────────
  time.timeZone = "Europe/Berlin";

  # ── Hardware enablement ──────────────────────────────────────────────────
  hardware.enableRedistributeOnLink = true;
  hardware.enableAllFirmware = true;

  # ── Audio (Pipewire is enabled in hyprland.nix) ──────────────────────────
  services.pipewire.enable = true;

  # ── Bluetooth (for headset/headphone convenience) ────────────────────────
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  # ── Printing (cups) ──────────────────────────────────────────────────────
  services.printing.enable = true;

  # ── System packages — minimal, user pkgs live in Home Manager ───────────
  environment.systemPackages = with pkgs; [
    vim                     # fallback in TTY
    wget curl git
    pciutils usbutils
    lm_sensors
    acpi
    htop
    networkmanager
    openssh
  ];

  # ── Allow unfree (some firmware blobs) ───────────────────────────────────
  nixpkgs.config = {
    allowUnfree = true;
    permittedInsecurePackages = [ ];
  };

  # ── Filesystem ───────────────────────────────────────────────────────────
  services.fstrim = {
    enable = true;
    interval = "weekly";
  };

  # ── GnuPG agent (for git signing / ssh) ──────────────────────────────────
  services.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
    defaultCacheTtl = 1800;
  };

  # ── OpenSSH server (off by default — enable if needed) ───────────────────
  services.openssh.enable = false;

  # ── Virtualisation (libvirt + docker daemon) ─────────────────────────────
  virtualisation.docker.enable = true;
  virtualisation.libvirtd.enable = true;
  programs.dconf.enable = true;
}